CREATE TABLE `res_image` (
`id` bigint(11) NOT NULL COMMENT '数据库id',
`res_id` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '资源编号',
`provider_res_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '供应原始编号',
`brand_id` int(8) DEFAULT NULL,
`provider_id` int(8) DEFAULT NULL COMMENT '供应商id',
`provider_agent_type` int(1) DEFAULT NULL COMMENT '供应商类型 1-机构 2-个人  3-500px摄影师',
`collection_id` int(8) DEFAULT NULL COMMENT '原始品牌id',
`cfp_gic_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'cfp、gic资源编号',
`asset_family` int(1) DEFAULT NULL COMMENT '媒资分类1编辑类2创意类',
`asset_type` int(2) DEFAULT NULL COMMENT '媒资类型1图片2视频3音频',
`license_type` int(1) DEFAULT NULL COMMENT '授权类型 1RM 2RF 3RR',
`graphical_style` int(2) DEFAULT NULL COMMENT '1-摄影图片 2-插画 10-模板（创意） 11-Icon（创意） 12-元素（创意） 3-漫画（编辑）4-图表（编辑）5-矢量图（编辑）6-psd（编辑）\n7-普通全景（编辑）8-360全景（编辑）',
`asset_format` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '媒资格式JPG, JPEG, GIF等',
`title` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '标题',
`caption` text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '***_***后面是原始图说，前面是新加图说',
`one_category` int(11) DEFAULT NULL COMMENT '一级分类',
`category` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '分类以，分割',
`quality_rank` int(1) DEFAULT NULL COMMENT '图片等级 1A 2B 3C 4D 5E ',
`keywords` varchar(2048) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '关键词',
`image_state` int(1) DEFAULT NULL COMMENT '1未编审 2已编审 3图片不通过 4图片审核通过 5关键词不通过',
`online_state` int(1) DEFAULT NULL COMMENT '1已上线2未上线3已下线',
`online_time` datetime DEFAULT NULL COMMENT '上线时间',
`offline_time` datetime DEFAULT NULL COMMENT '下线时间',
`offline_reason` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '下线原因',
`offline_mark` int(2) DEFAULT NULL COMMENT '0:初始状态1:标记下线 2:确认下线',
`keywords_reject_reason` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '自定义原因',
`image_reject_reason` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '标准原因',
`credit_line` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '图片署名',
`pic_width` int(8) DEFAULT NULL COMMENT '宽',
`pic_height` int(8) DEFAULT NULL COMMENT '高',
`pic_size` int(11) DEFAULT NULL COMMENT '存储大小,单位字节',
`color_type` int(1) DEFAULT NULL COMMENT '1黑白2彩色',
`date_camera_shot` datetime DEFAULT NULL COMMENT '拍摄时间',
`country` varchar(254) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
`province` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '省',
`city` varchar(254) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '城市',
`location` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '具体地点',
`people` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '人物名称',
`upload_time` datetime DEFAULT NULL COMMENT '入库时间',
`oss_yuantu` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '原图',
`oss_176` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '176',
`oss_800` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '800图无水印',
`oss_800_watermark` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '800图有水印',
`oss_400` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '400图无水印',
`oss_eps_jpg` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
`oss_id7` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
`edit_time` datetime DEFAULT NULL COMMENT '编审时间',
`edit_user_id` int(11) DEFAULT NULL COMMENT '编审用户id',
`is_postil` int(1) DEFAULT NULL COMMENT '是否批注1是0没批注',
`postil_time` datetime DEFAULT NULL COMMENT '批注时间',
`is_copyright` int(1) DEFAULT NULL COMMENT '是否有版权: \r\n0-不涉及肖像权或物权授权\r\n1-已取得肖像权授权\r\n2-已取得肖像权和物权授权\r\n3-已取得物权授权\r\n7-未取得物权授权\r\n9-未取得肖像权或物权授权',
`copyright` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '版权声明:  \r\n0-不涉及肖像权或物权授权\r\n1-已取得肖像权授权\r\n2-已取得肖像权和物权授权\r\n3-已取得物权授权\r\n7-未取得物权授权\r\n9-未取得肖像权或物权授权',
`maincolors` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '颜色',
`orientation` int(1) DEFAULT NULL COMMENT '横竖图1横图2竖图3方图',
`online_type` int(1) DEFAULT NULL COMMENT '只对创意类有效 0：质量审核+关键词审核 1：质量免审+关键词审核 2：质量审核+关键词免审  3：质量免审+关键词免审',
`min_price` int(11) DEFAULT NULL COMMENT '0-30, 3-500, 4-1000,5-1500, 9-特殊授权品牌资源',
`price` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0',
`memo` varchar(3000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '备注',
`created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
`created_by` varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
`updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`updated_by` varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `i_provider_res_id` (`provider_res_id`),
KEY `online_time` (`online_time`),
KEY `edit_time` (`edit_time`),
KEY `i_created_time` (`created_time`),
KEY `i_online_state` (`online_state`),
KEY `i_res_id` (`res_id`),
KEY `i_brand_id` (`brand_id`),
KEY `i_asset_family` (`asset_family`),
KEY `i_provider_id` (`provider_id`),
KEY `one_category` (`one_category`),
KEY `cfp_gic_id` (`cfp_gic_id`),
KEY `i_collection_id` (`collection_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='图片表';